val device_fns: string list
val alloc_fns: string list
val kernel_fns: string list
val sync_functions: string list
val dmaio_fns: string list
val portio_fns: string list
val mmio_functions: string list
val bus_functions: string list
val thread_functions: string list
val event_functions: string list
val alloc_dev: string list
val kernel_helper_libs: string list
val kernel_dev_libs: string list
val timer_fns: string list
val all_basic_fns: string list
